name: shell
on: [push,pull_request]
jobs: 
    run-shell-commands:
       runs-on: ubuntu-18.04
       steps:
          - name: ECHO A STRING
            run: echo "Prakash"

          - name: Multiline String 
            run: |
                 node -v
                 npm -v

    python-commands:
       runs-on: ubuntu-18.04
       steps:
          - name: Run a Python Program 
            run: python --version

          - name: python commands
            run: |
                 #!/usr/bin/python3
                 pip3 freeze